/// <autosync enabled="true" />
/// <reference path="jquery-ui-1.12.1.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="jquery-1.12.4.js" />
/// <reference path="bootstrap.js" />
/// <reference path="respond.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery.timepicker.js" />
/// <reference path="../content/mydesign/main.js" />
/// <reference path="../content/datepicker/datepicker.js" />
/// <reference path="../content/datepicker/datepickermin.js" />
/// <reference path="../content/timepicker/jquerytimepicker.js" />
/// <reference path="../content/masterpage/js/hoverintent.js" />
/// <reference path="../content/masterpage/js/jquery-ui.js" />
/// <reference path="../content/masterpage/js/mail-script.js" />
/// <reference path="../content/masterpage/js/main.js" />
/// <reference path="../content/masterpage/education - doc/js/custom.js" />
/// <reference path="../content/masterpage/education - doc/js/jquery.nav.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shautoloader.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushapplescript.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushas3.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushbash.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushcoldfusion.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushcpp.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushcsharp.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushcss.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushdelphi.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushdiff.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrusherlang.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushgroovy.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushjava.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushjavafx.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushjscript.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushperl.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushphp.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushplain.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushpowershell.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushpython.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushruby.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushsass.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushscala.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushsql.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushvb.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shbrushxml.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shcore.js" />
/// <reference path="../content/mydesign/jquery-3.2.1.js" />
/// <reference path="../content/masterpage/js/easing.js" />
/// <reference path="../content/masterpage/js/jquery.ajaxchimp.js" />
/// <reference path="../content/masterpage/js/jquery.magnific-popup.js" />
/// <reference path="../content/masterpage/js/jquery.nice-select.js" />
/// <reference path="../content/masterpage/js/jquery.tabs.js" />
/// <reference path="../content/masterpage/js/owl.carousel.js" />
/// <reference path="../content/masterpage/js/superfish.js" />
/// <reference path="../content/masterpage/education - doc/js/jquery-1.11.0.js" />
/// <reference path="../content/masterpage/js/vendor/bootstrap.js" />
/// <reference path="../content/masterpage/js/vendor/jquery-2.2.4.js" />
/// <reference path="../content/masterpage/education - doc/syntax-highlighter/scripts/shlegacy.js" />
